/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2019-09-29 20:20:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AddItem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Add Items</title>\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("\t\r\n");
      out.write("\tbackground:url('back1.png'); \r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction validate() {\r\n");
      out.write("\t\tvar itemid = document.form.itemid.value;\r\n");
      out.write("\t\tvar itemname = document.form.itemname.value;\r\n");
      out.write("\t\tvar type = document.form.type.value;\r\n");
      out.write("\t\tvar quantity = document.form.quantity.value;\r\n");
      out.write("\t\tvar unitprice = document.form.unitprice.value;\r\n");
      out.write("\t\tvar supplierid = document.form.supplierid.value;\r\n");
      out.write("\t\tvar date = document.form.date.value;\r\n");
      out.write("\r\n");
      out.write("\t\tif (itemid == null || itemid == \"\") {\r\n");
      out.write("\t\t\talert(\"Item ID can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (itemname == null || itemname == \"\") {\r\n");
      out.write("\t\t\talert(\"item Name can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (type == null || type == \"\") {\r\n");
      out.write("\t\t\talert(\"Item Type can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (quantity == null || quantity == \"\") {\r\n");
      out.write("\t\t\talert(\"Quantity can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (unitprice == null || unitprice == \"\") {\r\n");
      out.write("\t\t\talert(\"Unit Price can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (supplierid == null || supplierid == \"\") {\r\n");
      out.write("\t\t\talert(\"Supplier ID can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (date == null || date == \"\") {\r\n");
      out.write("\t\t\talert(\"Date can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div style=\"width:800px; margin:0 auto;\" >\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("\t\t<h1>Add a New Item</h1>\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("\t<form name=\"form\" action=\"AddItemServlet\" method=\"post\" onSubmit=\"return validate();\">\r\n");
      out.write("\t\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t\t<table cellpadding=\"3\" style=\"width: 50%\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr height=\"20\">\r\n");
      out.write("\t\t\t\t\t<td><p style=\"font-size: larger\">Item ID:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"itemid\" placeholder=\"I001\" autocomplete=\"off\" required/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr height=\"20\">\r\n");
      out.write("\t\t\t\t\t<td><p style=\"font-size: larger\">Item Name:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"itemname\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"cement\" autocomplete=\"off\" required /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr height=\"20\">\r\n");
      out.write("\t\t\t\t\t<td><p style=\"font-size: larger\">Select Item Type:</td>\r\n");
      out.write("\t\t\t\t\t<td><input list=\"status\" name=\"type\" placeholder=\"choose item type\"/></td>\r\n");
      out.write("\t\t\t\t\t<datalist id=\"status\"> <select required>\r\n");
      out.write("\t\t\t\t\t<option>Raw Materials</option>\r\n");
      out.write("\t\t\t\t\t<option>Tools</option>\r\n");
      out.write("\t\t\t\t\t<option>Equipments</option>\r\n");
      out.write("\t\t\t\t\t<option>Vehicles</option>\r\n");
      out.write("\t\t\t\t</select> </datalist>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr height=\"20\">\r\n");
      out.write("\t\t\t\t\t<td><p style=\"font-size: larger\">Quantity (kg/l):</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"quantity\" placeholder=\"1000\" autocomplete=\"off\" required/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr height=\"20\">\r\n");
      out.write("\t\t\t\t\t<td><p style=\"font-size: larger\">Unit Price (Rs.):</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"unitprice\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"100\" autocomplete=\"off\" required/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr height=\"20\">\r\n");
      out.write("\t\t\t\t\t<td><p style=\"font-size: larger\">Supplier ID:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name=\"supplierid\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"12\" autocomplete=\"off\" required/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr height=\"20\">\r\n");
      out.write("\t\t\t\t\t<td><p style=\"font-size: larger\">\r\n");
      out.write("\t\t\t\t\t\t\tStock in Date:</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"date\" name=\"date\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"2019-09-30\" autocomplete=\"off\" required/></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<table align=\"center\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\"><input type=\"submit\" value=\"Save Item\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>  \r\n");
      out.write("\t<center><a href=\"ListItemServlet\">View List of Items</a></center>\r\n");
      out.write("\t<br><br><br>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
