/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2019-09-29 18:25:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Register</title>\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("\t\r\n");
      out.write("\tbackground:url('back1.png'); \r\n");
      out.write("\tbackground-size: cover;\r\n");
      out.write("}\r\n");
      out.write("td{\r\n");
      out.write("\twidth:50%;\t\r\n");
      out.write("\theight:60px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction validate() {\r\n");
      out.write("\t\tvar username = document.form.username.value;\r\n");
      out.write("\t\tvar password = document.form.password.value;\r\n");
      out.write("\t\tvar conpassword = document.form.confirmpassword.value;\r\n");
      out.write("\t\tvar fullname = document.form.fullname.value;\r\n");
      out.write("\t\tvar nicno = document.form.nicno.value;\r\n");
      out.write("\t\tvar email = document.form.emailaddress.value;\r\n");
      out.write("\t\tvar streetaddress = document.form.streetaddress.value;\r\n");
      out.write("\t\tvar contactno = document.form.contactno.value;\r\n");
      out.write("\t\tvar regdate = document.form.regdate.value;\r\n");
      out.write("\r\n");
      out.write("\t\tif (username == null || username == \"\") {\r\n");
      out.write("\t\t\talert(\"Username can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (password == null || password == \"\") {\r\n");
      out.write("\t\t\talert(\"Password can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (password.length < 8) {\r\n");
      out.write("\t\t\talert(\"Password must be at least 8 characters long.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (password != conpassword) {\r\n");
      out.write("\t\t\talert(\"Confirm Password should match with the Password\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (fullname == null || fullname == \"\") {\r\n");
      out.write("\t\t\talert(\"Full Name can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (nicno == null || nicno == \"\") {\r\n");
      out.write("\t\t\talert(\"NIC Number can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (email == null || email == \"\") {\r\n");
      out.write("\t\t\talert(\"Email Address can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (streetaddress == null || streetaddress == \"\") {\r\n");
      out.write("\t\t\talert(\"Street Address can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (contactno == null || contactno == \"\") {\r\n");
      out.write("\t\t\talert(\"Contact Number can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (regdate == null || regdate == \"\") {\r\n");
      out.write("\t\t\talert(\"Registered Date can't be blank\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<center>\r\n");
      out.write("\t\t<h2 style=\"width: 100%; background-color: black; color: white;\">Registration\r\n");
      out.write("\t\t\tto the Procurement System</h2>\r\n");
      out.write("\t</center>\r\n");
      out.write("\r\n");
      out.write("\t<form style=\"text-align: left;\" name=\"form\" action=\"RegisterServlet\"\r\n");
      out.write("\t\tmethod=\"post\" onSubmit=\"return validate();\">\r\n");
      out.write("\t\t<table border=\"0\" cellpadding=\"0\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t<font color=\"red\">* These fields are required</font>\r\n");
      out.write("\t\t\t<tr height=\"0px\">\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\"><font color=\"blue\">Enter Login Details\r\n");
      out.write("\t\t\t\t\t\t\tHere</font></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<td><p style=\"font-size: larger\">Set Username *</td>\r\n");
      out.write("\t\t\t<td><input type=\"text\" name=\"username\"\r\n");
      out.write("\t\t\t\tplaceholder=\"set username\" class=\"box\" autocomplete=\"off\" required /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"0px\">\r\n");
      out.write("\t\t\t\t<td><p style=\"font-size: larger\">Set Password *</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"password\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"set password\" class=\"box\" autocomplete=\"off\" required /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"0px\">\r\n");
      out.write("\t\t\t\t<td><p style=\"font-size: larger\">Confirm Password *</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"password\" name=\"confirmpassword\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"confirm password\" class=\"box\" autocomplete=\"off\"\r\n");
      out.write("\t\t\t\t\trequired /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th colspan=\"2\"><font color=\"blue\">Enter Personal\r\n");
      out.write("\t\t\t\t\t\t\tDetails Here</font></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tr height=\"0px\">\r\n");
      out.write("\t\t\t\t<td><p style=\"font-size: larger\">Full Name *</td>\r\n");
      out.write("\t\t\t\t<td><input list=\"status\" name=\"fullname\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"full name\" class=\"box\" /></td>\r\n");
      out.write("\t\t\t\t<datalist id=\"status\">\r\n");
      out.write("\t\t\t\t\t<select required>\r\n");
      out.write("\t\t\t\t\t\t<option>Mr.</option>\r\n");
      out.write("\t\t\t\t\t\t<option>Mrs.</option>\r\n");
      out.write("\t\t\t\t\t\t<option>Ms.</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</datalist>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"0px\">\r\n");
      out.write("\t\t\t\t<td><p style=\"font-size: larger\">NIC Number *</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"nicno\" placeholder=\"xxxxxxxxxV\"\r\n");
      out.write("\t\t\t\t\tclass=\"box\" autocomplete=\"off\" required /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"0px\">\r\n");
      out.write("\t\t\t\t<td><p style=\"font-size: larger\">Email Address *</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"email\" name=\"emailaddress\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"email address\" class=\"box\" autocomplete=\"off\" required /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"0px\">\r\n");
      out.write("\t\t\t\t<td><p style=\"font-size: larger\">Street Address</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"streetaddress\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"street address\" class=\"box\" autocomplete=\"off\"\r\n");
      out.write("\t\t\t\t\trequired /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"0px\">\r\n");
      out.write("\t\t\t\t<td><p style=\"font-size: larger\">Contact Number *</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" name=\"contactno\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"contact number\" class=\"box\" autocomplete=\"off\"\r\n");
      out.write("\t\t\t\t\trequired /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"0px\">\r\n");
      out.write("\t\t\t\t<td><p style=\"font-size: larger\">Registered Date</td>\r\n");
      out.write("\t\t\t\t<td><input type=\"date\" name=\"regdate\" placeholder=\"yyyy-MM-dd\"\r\n");
      out.write("\t\t\t\t\tclass=\"box\" autocomplete=\"off\" required /></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>");
      out.print((request.getAttribute("errMessage") == null) ? "" : request.getAttribute("errMessage"));
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr height=\"0px\">\r\n");
      out.write("\t\t\t\t<td><input type=\"submit\" value=\"Register\"></input></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"reset\" value=\"Reset\"></input></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><center>\r\n");
      out.write("\t\t\t\t\t\tAlready registered!! <a href=\"Login.jsp\">Login Here</a>\r\n");
      out.write("\t\t\t\t\t</center></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
